//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NCWidgetProviding-Protocol.h"

@class NPWNowPlayingController, NPWScrubber, NSButton, NSImageView, NSString, NSTextField;

@interface NPWNowPlayingViewController : NSViewController <NCWidgetProviding>
{
    NSButton *_playPauseButton;
    NSButton *_scanForwardButton;
    NSButton *_scanBackwardButton;
    NSImageView *_albumImageView;
    NSTextField *_trackTextField;
    NSTextField *_artistTextField;
    NSTextField *_remainingTimeTextField;
    NSTextField *_elapsedTimeTextField;
    NPWScrubber *_scrubber;
    BOOL _disableScrubberUpdates;
    double _lastUpdateTime;
    BOOL _scanning;
    NPWNowPlayingController *_nowPlayingController;
}

@property(retain, nonatomic) NPWNowPlayingController *nowPlayingController; // @synthesize nowPlayingController=_nowPlayingController;
- (void).cxx_destruct;
- (void)_setScrubberEnabled:(BOOL)arg1;
- (void)_updatePlayPauseButton;
- (void)_updateScrubber;
- (void)_updateArtistAndTrackName;
- (void)_updateAlbumImage;
- (void)_updateEntireWidget;
- (void)_scrubberDragged:(id)arg1;
- (void)_scanButtonPressed:(id)arg1;
- (void)_playPauseButtonPressed:(id)arg1;
- (struct NSEdgeInsets)widgetMarginInsetsForProposedMarginInsets:(struct NSEdgeInsets)arg1;
- (void)widgetPerformUpdateWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly) BOOL widgetAllowsEditing;

@end

