//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSImage, NSNumber, NSString, NSTimer;

@interface NPWNowPlayingController : NSObject
{
    BOOL _isRegisteredForNowPlayingNotifications;
    NSTimer *_elapsedTimeUpdateTimer;
    double _lastElapsedTime;
    double _lastElapsedTimeUpdateTimestamp;
    double _playbackRate;
    BOOL _playing;
    NSString *_artistName;
    NSString *_trackName;
    NSImage *_albumImage;
    NSNumber *_computedElapsedTime;
    NSNumber *_duration;
    double _lastUpdateTime;
    BOOL _nowPlayingAppRegistered;
    NSString *_appName;
    NSImage *_appImage;
}

@property(readonly) NSImage *appImage; // @synthesize appImage=_appImage;
@property(readonly) NSString *appName; // @synthesize appName=_appName;
@property(readonly) BOOL nowPlayingAppRegistered; // @synthesize nowPlayingAppRegistered=_nowPlayingAppRegistered;
- (void)_setDuration:(double)arg1;
- (void)_setElapsedTime:(double)arg1;
- (void)_setAppImage:(id)arg1;
- (void)_setAlbumImage:(id)arg1;
- (void)_setAppName:(id)arg1;
- (void)_setTrackName:(id)arg1;
- (void)_setArtistName:(id)arg1;
- (void)_setLastUpdateTime:(double)arg1;
- (void)_updateTimeInfo;
- (void)_setLastElapsedTime:(double)arg1 timestamp:(double)arg2;
- (void)_setPlaying:(BOOL)arg1;
- (void)_setNowPlayingAppRegistered:(BOOL)arg1;
- (void)_updateWithNowPlayingClient:(void *)arg1;
- (void)_updatePlaybackState;
- (void)_updateNowPlayingInfo;
- (void)_updateNowPlayingAppRegistered;
- (void)_unregisterForNotifications;
- (void)_registerForNotifications;
- (void)endRewind:(id)arg1;
- (void)beginRewind:(id)arg1;
- (void)endFastForward:(id)arg1;
- (void)beginFastForward:(id)arg1;
- (void)skipBackward:(id)arg1;
- (void)skipForward:(id)arg1;
- (void)togglePlayback:(id)arg1;
- (void)pause:(id)arg1;
- (void)play:(id)arg1;
@property(readonly) NSNumber *duration;
@property(readonly) NSNumber *elapsedTime;
@property(readonly) NSImage *albumImage;
@property(readonly) NSString *trackName;
@property(readonly) NSString *artistName;
@property(readonly, getter=isPlaying) BOOL playing;
@property(readonly) double lastUpdateTime;
- (void)stopUpdatingTimeInfo;
- (void)startUpdatingTimeInfo;
- (void)dealloc;
- (id)init;

@end

