//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSSlider.h>

@class NSArray, NSDateComponentsFormatter;

@interface NPWScrubber : NSSlider
{
    NSArray *_loadedTimeRanges;
    NSDateComponentsFormatter *_dateComponentsFormatter;
}

+ (void)initialize;
- (id)accessibilityValueDescription;
- (struct CGSize)intrinsicContentSize;
- (double)baselineOffsetFromBottom;
- (struct NSEdgeInsets)alignmentRectInsets;
- (BOOL)allowsVibrancy;
- (void)setEnabled:(BOOL)arg1;

@end

